Permissions and fix for build_client

diff --git a/openvpn-clustered-server/service/build_client b/openvpn-clustered-server/service/build_client
--- a/openvpn-clustered-server/service/build_client
+++ b/openvpn-clustered-server/service/build_client
@@ -11,12 +11,31 @@ set -x
 client_name=$1
 client_type=$2
 
-source /service/scripts/helper.sh
+if [[ -z "${client_name}" ]]; then
+  echo "Client name is required" 1>&2
+  exit 1
+fi
 
 prefix=
 if [[ ! -z ${client_type} ]]; then
   prefix="${client_type}-"
 fi
+
+cd /data
+
+# Build the client pki
+/usr/share/easy-rsa/easyrsa build-client-full "${prefix}${client_name}" nopass
+# And generate the conf file
+/service/build_config client "${prefix}${client_name}"
+
+# If there is any script available to do additional actions, call it
+if [[ -f /service/server-build-client.sh ]]; then
+  /service/server-build-client.sh $@
+fi
+
+
+source /service/scripts/helper.sh
+
 
 clientConfig=/data/clients/${prefix}${client_name}.conf
 
